name: Auto Release

on:
  push:
    branches:
        - 'master*'
        
jobs:
    generate-release-tag:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ğŸ›ï¸
              uses: actions/checkout@v2.3.1
            - name: Setup Node
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: '16.x'
            - name: Setting up Github Identity ğŸ‘¤
              uses: fregante/setup-git-token@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                name: Bot Releaser
                email: prince@deriv.com
            - name: Fetch tags ğŸŒ€
              run: git fetch --unshallow --tags
            - name: Create new production tag ğŸš€
              run:  
                  npm run release
                

