name: Auto Release

on:
  push:
    branches:
        - 'master*'
        
jobs:
    automate-deployment:
        if: ${{ !startsWith(github.event.workflow_run.head_branch, 'no-auto-release') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout ğŸ›ï¸
              uses: actions/checkout@v2.3.1
            - name: Setup Node
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: '16.x'
            - name: Fetch tags ğŸŒ€
              run: git fetch origin
            - name: Echo merged branch name 
              run:  
                  echo ${{ github.event.workflow_run.head_branch }}
            - name: Create new production tag ğŸš€
              run:  
                  npm run release
                

