name: Auto Release

on:
  push:
    branches:
        - 'master*'
        
jobs:
    generate-release-tag:
        if: ${{ !startsWith(github.event.workflow_run.head_branch, 'no-auto-release') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout üõéÔ∏è
              uses: actions/checkout@v2.3.1
            - name: Setup Node
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: '16.x'
            - name: Fetch tags üåÄ
              run: git fetch origin
             - name: Print Github Variables
              run: |
                echo "GITHUB_WORKFLOW:$GITHUB_WORKFLOW"
                echo "GITHUB_EVENT_NAME:$GITHUB_EVENT_NAME"
                echo "GITHUB_EVENT_PATH:$GITHUB_EVENT_PATH"
                echo "GITHUB_WORKSPACE:$GITHUB_WORKSPACE"
                echo "GITHUB_SHA:$GITHUB_SHA"
                echo "GITHUB_REF:$GITHUB_REF"
                echo "GITHUB_HEAD_REF:$GITHUB_HEAD_REF"
            - name: Create new production tag üöÄ
              run:  
                  npm run release
                

